[package]
name = "ip32prom-decompiler"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
capstone = "0.14"
byteorder = "1.5"
anyhow = "1.0"
clap = { version = "4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
